### ISSUE TITLE
undefined: proto.SizeVarint

### ISSUE THREAD

**Issue by coyle** [gengo/grpc-gateway#103]
Getting the following error when attempting to run ```go get github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway```

![image](https://cloud.githubusercontent.com/assets/2541605/12821529/c7e611ca-cb31-11e5-9199-0eb6cf37a6a1.png)

**Comment by shurcooL** [comment]
One of your dependencies is out of date. Using `-u` flag will fix that and allow it to work.

```bash
go get -u github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway
```

**Comment by coyle** [comment]
Thanks @shurcooL !
