### ISSUE TITLE
go vet issues in template_test.go

### ISSUE THREAD

**Issue by shawnps** [gengo/grpc-gateway#113]
I'm not sure what the string should be otherwise I would have made the PR myself, but there are multiple `go vet` issues in `protoc-gen-swagger/genswagger/template_test.go`:

https://goreportcard.com/report/github.com/gengo/grpc-gateway#go_vet

**Comment by shawnps** [comment]
(Maybe just remove the `file` argument in the `Errorf` calls)

**Comment by achew22** [comment]
I'm the author on those. I absently mindedly wrote "file" in there when I wanted to write %s. Thanks for doing all this cleanup!

**Comment by shawnps** [comment]
@achew22 np. If you like what I found, please consider adding a Go Report Card badge to the README :+1: 

`[![Go Report Card](https://goreportcard.com/badge/github.com/gengo/grpc-gateway)](https://goreportcard.com/report/github.com/gengo/grpc-gateway)`
