### ISSUE TITLE
support protobuf-over-HTTP

### ISSUE THREAD

**Issue by tamird** [gengo/grpc-gateway#124]
It'd be cool to provide encoded protobuf support in addition to JSON from the endpoints generated by grpc-gateway. This can be done by switching on the incoming request's content type as is done in `MarshalResponse` and `UnmarshalRequest` in https://github.com/cockroachdb/cockroach/blob/master/util/http.go

**Comment by philips** [comment]
@tamird that is a cool use case. But, I think you missed a line number anchor in your example.

**Comment by tamird** [comment]
Didn't intend to line anchor - look for the functions I mentioned by name.

**Comment by tamird** [comment]
This is sufficiently supported now. See https://github.com/cockroachdb/cockroach/pull/6754 for an example.
