### ISSUE TITLE
protoc-gen-swagger comment parsing for documentation gen

### ISSUE THREAD

**Issue by jacmarjorie** [gengo/grpc-gateway#128]
Is there, by chance, any documentation on how to properly format comments so that the swagger fields in the JSON will be nicely populated for documentation purposes?

**Comment by achew22** [comment]
Unfortunately that is not something that I implemented. Fortunately I don't think it would be extremely difficult if you wanted to take a swing at contributing.

The comments are in the [SourceCodeInfo_Location](https://godoc.org/github.com/golang/protobuf/protoc-gen-go/descriptor#SourceCodeInfo_Location) object inside the [FileDescriptorProto](https://godoc.org/github.com/golang/protobuf/protoc-gen-go/descriptor#FileDescriptorProto) when [genswagger](https://github.com/gengo/grpc-gateway/blob/master/protoc-gen-swagger/genswagger/template.go) iterates over the files.

If you need more pointers than that please comment on this issue and I'll see what I can do.

Thanks for reaching out!

**Comment by kellrott** [comment]
It looks like #134 covers this issue. Hopefully that will be merged in soon.
