### ISSUE TITLE
push to web clients using WS or SSE ?

### ISSUE THREAD

**Issue by joeblew99** [gengo/grpc-gateway#131]
Does this generate any push functionality ? For example Websockets, etc etc

Does it make sense that a bit directions system like GRPC is begging to be proxied via web sockets ? 

I think that SSE would be easier, having read a bit about it.

**Comment by joeblew99** [comment]
https://www.youtube.com/watch?v=qHrS0lqeZeo&nohtml5=False

looks like google have implemented something kind of similar to this in golang, but also they do not support streams. they added service discovery and some nice tooling..

**Comment by yugui** [comment]
Yeah.
Currently grpc-gateway does not support push notification very well.  I don't have a plan to support it because it looks to be too much for typical use cases.

**Comment by joeblew99** [comment]
Might be worth checking out luci-go repo.
It's by Google appengine team.
They are doing similar stuff to this repo in regards to grpc.
It's not easy to find - it's a huge repo.


https://github.com/luci/luci-go/


One ref to help:
https://github.com/luci/luci-go/blob/master/client/cmd/rpc/call.go

They are also not supporting streaming back up to a browser using WS or SSE as far as I can tell.

**Comment by yugui** [comment]
Thank you for the pointers.

The purpose of pRPC and the one of grpc-gateway are different. They are trying to transport something similar to gRPC over HTTP/1.1. In particular, it allows users to run their gRPC application in classic Go runtime of AppEngine. Also they allow users to reuse existing service implementation in process, but the implementation must be in Go.

grpc-gateway intend to provide traditional JSON-based RESTful APIs on top of other gRPC services. It cannot run in the same process as the services, but it does not require the services to be in Go. Also its handers are compatible to `net/http`.  So you can use the generated proxies as building blocks in your application server.
