### ISSUE TITLE
Does grpc-gateway support http middleware?

### ISSUE THREAD

**Issue by liaoliaopro** [gengo/grpc-gateway#132]
I would like to add some middlewares like CORS, gzip etc. for the generated rest api. Is there an easy way to do that? thanks.

**Comment by yugui** [comment]
It is designed to be compatible to standard golang interfaces.  So you can combine any middleware for standard libraries.

In particular, [Request multiplexer](https://godoc.org/github.com/gengo/grpc-gateway/runtime#ServeMux) implements the standard HTTP handler interface.
So you can easily combine it with such middleware in Gorilla. https://godoc.org/github.com/gorilla/handlers

**Comment by liaoliaopro** [comment]
@yugui  That help a lot. Great thanks!
