### ISSUE TITLE
Handling of import public "file.proto"

### ISSUE THREAD

**Issue by fiorix** [gengo/grpc-gateway#139]
When I use `import public "file.proto"` the generated .pb.go file contains my API + the public import ones. However, the pb.gw.go file does not.

Is that expected, am I missing something?

**Comment by yugui** [comment]
It might be a bug because I didn't consider `import public` when I implemented the code generator.
But I am not sure if I understand the problem you saw for the same reason.

Could you give me a more concrete example, what you expected and what you got?

**Comment by fiorix** [comment]
I had like 3 proto files used for specific things. Then elsewhere in another proto file I would `import public` all of them, and generate the proxy for the entire API. The .pb.go comes out right, but the .gw.go one does not include anything from the imported files.

**Comment by yugui** [comment]
I guess a scenario something like the followings.
* You had `a.proto`, `b.proto` and `c.proto` in a package.  `a.proto` contained something like
   ```protobuf
   message A{ }
   ```
* You also had another file `x.proto` in another package, which contained
  ```protobuf
  ```

**Comment by fiorix** [comment]
a.proto:

```
syntax = "proto3";

package a;

service Echo {
	rpc Echo(EchoRequest) returns (EchoResponse) {}
}

message EchoRequest {
	string Text = 1;
}

message EchoResponse {
	string Text = 1;
}
```

b.proto:

```
syntax = "proto3";

package b;

service Ping {
	rpc Ping(PingRequest) returns (PingResponse) {}
}

message PingRequest {
	string Text = 1;
}

message PingResponse {
	string Text = 1;
}
```

root.proto:

```
syntax = "proto3";

package root;

import public "a.proto";
import public "b.proto";
```

When I generate the .pb.go I get all types from a and b. The gateway and swagger ones are empty.

**Comment by yugui** [comment]
You won't see message definition unless it is actually used in services.
You never see message definition at all in `.gw.go` because it is intended to be compiled together with `.pb.go`.

**Comment by fiorix** [comment]
Sure, thanks!
