### ISSUE TITLE
recent annotation change requires req.RemoteAddr to be populated

### ISSUE THREAD

**Issue by tmc** [gengo/grpc-gateway#177]
a5edb0b39c61f3a90d5291cc04fe3e58f2fb77a7  merge resolution added `grpclog.Printf("invalid remote addr: %s", req.RemoteAddr)` which created a dependency on the incoming request that wasn't there before. Shouldn't the header just not be populated if RemoteAddr isn't present?

**Comment by yugui** [comment]
You are right.  We need to fix that part.
