### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by onlyjob** [gengo/grpc-gateway#189]
Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by yugui** [comment]
Sounds good.
For now, I'll tag it as a v0.1.0.  [Moving to grpc-ecosystem](https://github.com/gengo/grpc-gateway/issues/179) would be a good opportunity to tag it as v1.0.0.

**Comment by onlyjob** [comment]
Thank you. :)
