### ISSUE TITLE
Multiple .proto files generates invalid import statements.

### ISSUE THREAD

**Issue by tmc** [gengo/grpc-gateway#22]
passing multiple .proto files that include an import generates invalid import lines.

ex: compile a.proto and b.proto together with a importing b:
```go
import (
proto_0 "b.pb"
)
```
would be generated.

**Comment by yugui** [comment]
Probably it is working as intended but `protoc-gen-grpc-gateway` should have had more explicit error checks.

`protoc-gen-grpc-gateway` should have rejected code generation requests which contain two or more number of target packages, as `protoc-gen-go` does.  I guess it is the case.

It would be helpful if you show an example of `a.proto` and `b.proto`.

**Comment by yugui** [comment]
Actually that part of the behavior of `protoc-gen-go` is inconsistent and insane.  Let me think how to follow the behavior.

**Comment by mwitkow-io** [comment]
Yup, I'm hitting the same example:
```
	google_protobuf_0 "google/protobuf/empty.pb"
	google_protobuf_1 "google/protobuf/any.pb"
```

**Comment by mwitkow-io** [comment]
It seems that the way that the `gen-go` handles this is just importing the same thing multiple times:

Here's an example of `google/protobuf/api.pb.go`:

```go
import proto "github.com/golang/protobuf/proto"
import google_protobuf1 "improbable.io/proto_gen/google/protobuf"
import google_protobuf3 "improbable.io/proto_gen/google/protobuf"
```

So maybe just drop the filename at the end?
