### ISSUE TITLE
Format Errors to JSON

### ISSUE THREAD

**Issue by robstrong** [gengo/grpc-gateway#25]
Would it make sense to have some way to format the errors received from the RPC call into JSON? Currently, this [function](https://github.com/gengo/grpc-gateway/blob/f748a4771dce6d6974393fdace000eba85fd24a3/runtime/errors.go#L57) is called when an error occurs. A client of the HTTP server would be expecting JSON in the response though.

The response code is available which could indicate the error type but passing along an error message in JSON would be useful for the client.

Thoughts?

**Comment by yugui** [comment]
+1
