### ISSUE TITLE
Breaks with 1.5rc1 due to "internal" package name.

### ISSUE THREAD

**Issue by tmc** [gengo/grpc-gateway#36]

**Comment by shurcooL** [comment]
What's the error exactly?

**Comment by tmc** [comment]
```
package foobar
	imports github.com/gengo/grpc-gateway/internal: use of internal package not allowed
```

**Comment by yugui** [comment]
Ah, I understand.

Are you talking about the same one as this design doc?
https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit
