### ISSUE TITLE
Integrate authentication

### ISSUE THREAD

**Issue by yugui** [gengo/grpc-gateway#4]
Also relay credentials too in addition to method invocation itself.

**Comment by philips** [comment]
Do you have a rough idea how you would like to see this happen?

**Comment by yugui** [comment]
Originally I thought of terminating OAuth2 authorization in the gateway.

But I have started to think that it will work fine enough and is more consistent to google.api.http to 
just forward some HTTP headers as CallOptions.

**Comment by philips** [comment]
Sounds good. I like this plan.
