### ISSUE TITLE
Reverse the code gen idea

### ISSUE THREAD

**Issue by gedw99** [gengo/grpc-gateway#44]
I would like it is this translates a grpc into a  RESTful JSON api. 
This is the opposite of what the code currently does, accordion to the docs.

The reason I am wanting this is because its more bottom up. I typically build my service api, and generate the service proxy from it, and then get the web site to use that.

If there is any confusion please ask me

**Comment by shurcooL** [comment]
I think it already does what you want, if I understand you correctly.

The description says:

> It reads gRPC service definition, and generates a reverse-proxy server which translates a RESTful JSON API into gRPC.

The code it generates ends up translating RESTful JSON API into gRPC, but in other words it exposes a RESTful API from the existing gRPC service definition you already have.

**Comment by gedw99** [comment]
OK that's clearer.

I will definitely give this a try thanks

**Comment by yugui** [comment]
Probably we should have a cool diagram in the README page to help people to catch the idea at a glance.

**Comment by gedw99** [comment]
diagrams do help.

**Comment by tmc** [comment]
@yugui I think this issue can be closed -- it's just confusing for newcomers.

**Comment by yugui** [comment]
@tmc sure.
