### ISSUE TITLE
Header Forwarding from server.

### ISSUE THREAD

**Issue by sadlil** [gengo/grpc-gateway#73]
@yugui  With the specified header Prefix we can forward header from gateway to the grpc server and can get it within the context. But can't forward header from the server to the client with the gateway.

Grpc server can send header with the context with
```go
grpc.SendHeader(context, header-metadata)
```
But the header is truncated in the gateway. The forwarded header is not received by the client.
Are there any work progress in it or any other ways to doing it.

**Comment by yugui** [comment]
#93 helps us to forward headers (and trailers).

Also it would be better to let the gateway forward them by default.

**Comment by yugui** [comment]
Solved by #93
