### ISSUE TITLE
Support oneof types of fields

### ISSUE THREAD

**Issue by yugui** [gengo/grpc-gateway#82]
Extracted from #5.

Currently oneof fields are not supported. They should be allowed in request body and query string as well as other types.
* This feature requires #79 because `"encoding/json".Marshal` returns error for oneof fields
* No plan to allow them in path parameters because path parameters are "mandatory" parameters.  So they don't fit to `oneof` very well.

**Comment by JohanSJA** [comment]
Perhaps use of https://godoc.org/github.com/golang/protobuf/jsonpb instead of encoding/json can help.

**Comment by yugui** [comment]
@JohanSJA Thank you.  Yes, it is #79.

**Comment by gyuho** [comment]
@yugui etcd is hitting this issue, though it's happening only in experimental feature.

Do we have any workaround for this? Or ETA to support this?

Thanks!

**Comment by JohanSJA** [comment]
You should be able to use `one_of` with the help of `runtime.WithMarshalerOption`.

**Comment by yugui** [comment]
Now the default marshaller uses 'jsonpb'.  So I think it is supported.
https://travis-ci.org/gengo/grpc-gateway/jobs/137727616#L1049

@gyuho Could you re-confirm with the HEAD of the master branch?
Let me know if you still have the issue.
I'll close this issue if otherwise.

**Comment by gyuho** [comment]
@yugui First thanks for helping debugging this.

etcd still complains `{"Error":"json: cannot unmarshal object into Go value of type etcdserverpb.isWatchRequest_RequestUnion","Code":2}`. And tried the latest master branch of grpc-gateway and golang/protobuf, and regenerate the gateway files, as here https://github.com/coreos/etcd/pull/5891/commits/87592304b2c095425e224f289e122143c8e27487.

I added `reflect.TypeOf(marshaler)` to this line https://github.com/gyuho/etcd/blob/3108859828f851e9a46772fe8e16d257b40f3639/etcdserver/etcdserverpb/rpc.pb.gw.go#L91 and confirm that `*runtime.JSONPb` typed marshaler is being used, but still seeting that error.

```
*runtime.JSONPb
2016-07-06 22:07:13.861689 I | v3rpc/grpc: Failed to decode request: json: cannot unmarshal object into Go value of type etcdserverpb.isWatchRequest_RequestUnion
```

Maybe we generate gateway files in the wrong way? I tried to regenerate `*.gw.go` files but don't see any diff.

Thanks.

**Comment by yugui** [comment]
@gyuho I see. I'll take a look.

**Comment by yugui** [comment]
@gyuho 
Does this work fine?

```shell
curl -L http://localhost:2379/v3alpha/watch -X POST -d '{"create_request": {"key": "Zm9v"}}'
```

You need to specify literally one of the fields grouped by `request_union`.

**Comment by gyuho** [comment]
@yugui Still doesn't seem to work.

```
curl -L http://localhost:2379/v3alpha/watch -X POST -d '{"create_request": {"key": "Zm9v"}}'

{"Error":"unknown field \"create_request\" in etcdserverpb.WatchRequest","Code":2}
```

Thanks!

**Comment by yugui** [comment]
@gyuho 
It does not look to be an issue of grpc-gateway.  I could reproduce the issue without grpc-gateway.
```go
package main

import (
        "log"

        "github.com/coreos/etcd/etcdserver/etcdserverpb"
        "github.com/golang/protobuf/jsonpb"
)

func main() {
        const input = `{"create_request": {"key": "Zm9v"}}`
        var protoReq etcdserverpb.WatchRequest
        if err := jsonpb.UnmarshalString(input, &protoReq); err != nil {
                log.Fatal(err)
        }
}
```

```console
$ go run main.go
2016/07/12 12:15:28 unknown field "create_request" in etcdserverpb.WatchRequest
exit status 1
```

I don't know what the root cause actually is, but I suspect incompatibility between `github.com/golang/protobuf/jsonpb` and gogoproto-generated code.

**Comment by yugui** [comment]
@gyuho Confirmed in https://gist.github.com/yugui/4425e705680fb4f6c99423b99b8a83d2

```console
$ go get gist.github.com/4425e705680fb4f6c99423b99b8a83d2.git
$ go build -o test gist.github.com/4425e705680fb4f6c99423b99b8a83d2.git
$ ./test
$ echo $?
0
$ go build --tags=gogo -o test gist.github.com/4425e705680fb4f6c99423b99b8a83d2.git
$ ./test
2016/07/12 12:53:05 unknown field "create_request" in main.WatchRequest
$ echo $?
1
```

**Comment by gyuho** [comment]
@yugui I will see if I can find some workarounds or file an issue to gogoproto. Thanks a lot!

**Comment by yugui** [comment]
@gyuho 
I am not yet confident but I suspect if this `proto` in `(*WatchRequest).XXX_OneofFuncs`,
> `func (*WatchRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {`

at https://github.com/gyuho/etcd/blob/3108859828f851e9a46772fe8e16d257b40f3639/etcdserver/etcdserverpb/rpc.pb.go#L1084
 should have been `github.com/golang/protobuf/proto` but not `github.com/gogo/protobuf/proto` so that it is compatible to https://github.com/golang/protobuf/blob/ba6f978a1a6606adf3ccb6987f15c64262bfdbc2/proto/properties.go#L729.
