### ISSUE TITLE
Emit API definition in Swagger schema format

### ISSUE THREAD

**Issue by yugui** [gengo/grpc-gateway#9]
Swagger provides a good way to generate API references and client libraries of the REST API.
So we should have a way to generate swagger schema from .proto file to leverage with Swagger.

**Comment by ceram1** [comment]
I'm currently working on it, and do you have any idea about api reponse status code?
[grpc-gateway/runtime#HTTPStatusFromCode](http://godoc.org/github.com/gengo/grpc-gateway/runtime#HTTPStatusFromCode) returns http status code from grpc error code, but I can't get error code from doc generator.

How about defining all?

**Comment by ceram1** [comment]
+ Some protobuf file to declare swagger fields is required.

**Comment by ceram1** [comment]
One additional note.
Google discovery doc seems like a fork of swagger without error codes.

**Comment by philips** [comment]
@ceram1 Can you post your current WIP branch somewhere?

**Comment by ceram1** [comment]
@philips Sorry for delay.

I uploaded on ceram1/grpc-gateway@3fcd9e2

It's just a backup commit, as I could not finish swagger support.

I used this command to test this, from ```$GOPATH/src/github.com/gengo/grpc-gateway/```
```
go install ./protoc-gen-swagger/ && protoc -I. -I$GOPATH/src -I$GOPATH/src/github.com/gengo/grpc-gateway/third_party/googleapis  --swagger_out=. examples/a_bit_of_everything.proto 
```

**Comment by gosuri** [comment]
hey @ceram1, great job on swagger spec! How's it coming along?

**Comment by ceram1** [comment]
@gosuri I can't do it more, but it will not be hard to build a google discovery document generator.

**Comment by gosuri** [comment]
Gotcha! No worries :)

**Comment by achew22** [comment]
I think this can now be closed
