### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by mastermix252** [gengo/grpc-gateway#90]
Hello gengo,

I'm very happy that you've addressed a problem which many of gRPC consumers will have. The internal use of gRPC is useful, fast and reliable. But serving RPCs for external use will be difficult.
This is where the RESTful API as hybrid solution with gRPC comes in. 

My question is if this works already with NodeJS, I can't figure out how to implement it. If not, are you interested in implementing a solution for NodeJS as proxy.

Kind regards,
mastermix252

**Comment by yugui** [comment]
What do you want to do with NodeJS?

I think grpc-gateway works fine even if you write your gRPC server with NodeJS.  But I guess you are talking about something different.

**Comment by mastermix252** [comment]
Misunderstanding from my site. It works fine!

**Comment by dranzboi** [comment]
> Misunderstanding from my site. It works fine!

Hi, could you provide example, how it works, i can find way how to run it correctly
