### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by peter-edge** [gengo/grpc-gateway#92]
Hey,

Old topic, simpler idea: I don't want to re-invent the wheel, but can we do something similar to https://github.com/grpc/grpc-go/tree/master/grpclog for gprc-gateway? Using glog means everyone is locked into glog's very opinionated way of storing output, and it means in a lot of cases (including mine) that I just completely lose grpc-gateway logs.

The only change in the code would be to get rid of v-level logging, but I mean this is minor as I see it within the code.

**Comment by yugui** [comment]
I agree on its benefit. But I prefer simply using `grpclog` package.
What do you think?

**Comment by shurcooL** [comment]
Wasn't there a very similar proposal before? https://github.com/gengo/grpc-gateway/pull/54 Or is this different?

**Comment by yugui** [comment]
I don't remember why I closed #54.  But maybe I confused it with adding dependency to `dlog`?

I did not want to add extra dependency for that small improvement.  But `grpclog` is free from that concern.

**Comment by peter-edge** [comment]
Fine with me!

**Comment by peter-edge** [comment]
I can put together a PR

**Comment by crast** [comment]
Any reason not to simply use the package google.golang.org/grpc/grpclog directly? There's already a hard dependency on google.golang.org/grpc and this package is always at risk of dealing with the API changes in GRPC

I would assert that people who want to set the logging output for GRPC probably don't necessarily need to set different logging output for GRPC gateway - they generally either want it going somewhere they can control it, or they want it fully off

**Comment by yugui** [comment]
@crast You are right.  I am fine with `grpclog`.
