### ISSUE TITLE
Generation of one swagger file out of multiple protos?

### ISSUE THREAD

**Issue by FabianHinz** [gengo/grpc-gateway#99]
Hi,

First I want to thank you for creating this extremely useful tool!

Now this is probably more on the level of protoc than grpc-gateway but only concerns me regarding a RESTful API. 

It is only possible to generate one *.swagger.json file out of one .proto file and not out of multiple files? (same for *.pb.gw.go) I am currently planning new software that should have a very modular structure and will most likely end up with a lot of .proto file. That makes the swagger generator more or less useless for me, doesn't it?

Thank you and kind regards,

Fabian

**Comment by zxy198717** [comment]
@naibaf0 Did you solved this issue?

**Comment by naibaf0** [comment]
Hi @zxy198717 
If I remember correctly, no I didn't. We just settled on merging the proto files for swagger generation and since the specific project ended up on the backburner anyways I didn't look into it more.

**Comment by Rio** [comment]
We're running into the same issue now. Creating a client for each service on the browser side is something our frontenders would like to avoid. But seems to us that for now that's how it is. Until we're a bit more sure about our pipeline and api setup we're keeping the multiple clients.

**Comment by achew22** [comment]
Generating all those files as a single output is, IMO antithetical to the way protoc works. If someone wanted to write a small script in go that merged the outputs of multiple swagger definitions (we have the structs already defined so it wouldn't be that hard), it would be a welcome contribution to the project.
